### PR TITLE
Several improvements

### PR DESCRIPTION
**Pull request by richardstrnad**
- Implemented some issues (#53, #57)
- Extended test cases
- Better Vlan classification
- Added several interface properties

### CODE REVIEW

**Comment by XenonR** [comment]
Hmm, will anything happen here?

**Comment by mpenning** [comment]
@XenonR thank you for submitting patches; I will review and integrate when I get more time free.  May I ask about your specific interest in contributing all these patches?

**Comment by XenonR** [comment]
@mpenning thanks for the information. We're actually preparing a configuration audit and found ```ciscoconfparse``` a good starting point for developing the necessary tools. Therefore we expanded the functionality were needed. Additionally we implemented some issues and improved a few test cases.

**Comment by mpenning** [comment]
No need to implement this PR since you're supporting your own branch

**Comment by XenonR** [comment]
@mpenning You're right we duplicated our codebase and mirrored it under [YtenSoftware/Nety](https://github.com/YtenSoftware/Nety).
After several months of no living sign on this project we decided to give this project more love.
But anyhow i have hard times to understand why you don't want to implement our changes anyway.

Please keep in mind: I'm no native speaker, so no offense intended.

Regards

**Comment by mpenning** [comment]
@richardstrnad and @XenonR ,

Your PR had some good ideas, but I'm picky about how the code is written... things should scale well... my opinion is that these implementations in 1.2.42 will scale well and confirm to the general style that I use throughout the project.

Thank you for your suggestions, and for caring for Github issues while I've been otherwise occupied.

**Pull request closed without merging**
